language: java

filter_secrets: false
cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - os: linux
      jdk: openjdk11
    - os: windows
      language: generic
      before_install:
        - choco install openjdk11 -y

install: true
script: ./mvnw clean install
