language: java

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - os: linux
      jdk: openjdk11
    - os: windows
      language: shell
      before_install:
        - choco install openjdk11 --version 11.0.5.10;
        - export JAVA_HOME='/c/Program Files/OpenJDK/openjdk-11.0.5_10'
        - export PATH="${PATH}:${JAVA_HOME}/bin";

install: true
script: ./mvnw clean install
