language: java

sudo: false
cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - os: linux
      jdk: openjdk11
    - os: windows
      language: generic

install:
  - ./.travis/install.sh

script: ./mvnw clean install
