language: java

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - os: linux
      jdk: openjdk11
    - os: windows
      language: shell
      before_install:
        - choco install openjdk11 -y
        - refreshenv

install: true
script: ./mvnw clean install
